"""Authored ASS track grammar, name binding, and legacy rendering regressions."""
from __future__ import annotations

import copy
import logging
import os
from pathlib import Path
import random
import sys
import tempfile
import unittest
from unittest.mock import patch
import zipfile

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "skills/revayat-subtitle/scripts"
sys.path.insert(0, str(SCRIPTS))
import markup
import render
import runtime
import subtitle_formats as formats
import workflow

RENDER = "--render" in sys.argv or os.environ.get("REVAYAT_TEST_RENDER") == "1"
SIGNATURE = "; Script generated by FFmpeg/Lavc57.0.100"


def style(name="Default", colour="&H00FFFFFF"):
    values = formats.DEFAULT_STYLE.split(",")
    values[:4] = [name, "Arial" if os.name == "nt" else "DejaVu Sans", "42", colour]
    return "Style: " + ",".join(values)


def event(text="VISIBLE", name="Default", label="Dialogue"):
    return label + ": 0,0:00:01.00,0:00:03.00," + name + ",,0,0,0,," + text


def source(styles=None, *, name="Default", text="VISIBLE", headers="", extra=""):
    return ("[Script Info]\nScriptType: v4.00+\nPlayResX: 320\nPlayResY: 180\n" + headers +
            "\n[V4+ Styles]\nFormat: " + formats.STYLE_FIELDS + "\n" +
            "\n".join([style()] if styles is None else styles) +
            "\n[Events]\nFormat: " + formats.ASS_FIELDS + "\n" + event(text, name) + "\n" + extra)


class TrackWorkspace(unittest.TestCase):
    def setUp(self):
        scratch = ROOT / ".scratch/track-contracts"
        scratch.mkdir(parents=True, exist_ok=True)
        temporary = tempfile.TemporaryDirectory(prefix="authored-", dir=scratch)
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name).resolve()
        self.work = self.root / "workspace"
        self.environment = patch.dict(os.environ, {"REVAYAT_LOG_DIR": str(self.root / "logs")})
        self.environment.start()
        self.addCleanup(self.environment.stop)
        logging.debug("ASS track regression case=%s", self.id())

    def edition(self, texts):
        inputs = []
        for index, text in enumerate(texts):
            path = self.root / f"source-{index}.ass"
            path.write_text(text, encoding="utf-8")
            inputs.append(path)
        workflow.prepare(inputs, self.work, "Authored track", 1, "utf-8", None, "en")
        project = runtime.read_json(self.work / "project.json")
        project["episodes"] = [{"id": f"S01E{index:02}", "base": item["id"],
                                "comparison": "One authored source for this controlled episode"}
                               for index, item in enumerate(project["sources"], 1)]
        runtime.write_json(self.work / "project.json", project)
        for item in project["sources"]:
            sheet = self.work / "worksheets" / (item["id"] + ".json")
            rows = runtime.read_json(sheet)
            for row in rows:
                row.update(reviewed=True, action="preserve")
            runtime.write_json(sheet, rows)
        runtime.write_json(self.work / "glossary.json", {"series": "Authored track", "terms_reviewed": True,
            "terms": [], "research": [{"url": "https://example.org/authored", "note": "Authored fixture, not anime research"}]})
        return workflow.build(self.work)

    def pixels(self, label, text):
        path = self.root / (label + ".ass")
        path.write_text(text, encoding="utf-8")
        logging.debug("Rendering authored ASS oracle=%s", label)
        raw = runtime.run([render.ffmpeg_path(), "-hide_banner", "-loglevel", "error", "-nostdin",
            "-f", "lavfi", "-i", "color=c=0x202020:s=640x360:r=1:d=1", "-filter_threads", "1",
            "-vf", f"setpts=PTS+1.5/TB,ass={path.name}", "-frames:v", "1", "-threads", "1",
            "-pix_fmt", "rgb24", "-f", "rawvideo", "pipe:1"], cwd=self.root,
            timeout=20, idle_timeout=15, max_output=2 * 1024 * 1024)
        self.assertEqual(len(raw), 640 * 360 * 3)
        return raw


class GrammarTests(TrackWorkspace):
    def test_noncanonical_dialogue_refused(self):
        for label in ("dialogue", "DIALOGUE", "Dialogue ", "Dialogue\t"):
            with self.subTest(label=label), self.assertRaisesRegex(ValueError, "canonical"):
                formats.parse(source(extra=event("IGNORED", label=label)), "ass")

    def test_noncanonical_style_format_and_comment_refused(self):
        for old, new in (("Style:", "style:"), ("Format:", "format:"), ("Style:", "Style :")):
            with self.subTest(new=new), self.assertRaisesRegex(ValueError, "canonical"):
                formats.parse(source().replace(old, new, 1), "ass")
        with self.assertRaisesRegex(ValueError, "canonical"):
            formats.parse(source(extra=event("Note", label="comment")), "ass")

    def test_ascii_section_and_field_case_is_supported(self):
        text = source().replace("[Events]", "[eVeNtS]").replace("[V4+ Styles]", "[v4+ StYlEs]")
        text = text.replace(formats.ASS_FIELDS, formats.ASS_FIELDS.swapcase())
        doc = formats.parse(text, "ass")
        self.assertEqual(len(doc.cues), 1)
        self.assertEqual(formats.parse(formats.serialize(doc, doc.cues), "ass").cues[0].text, "VISIBLE")

    def test_unicode_field_lookalike_is_not_activated(self):
        text = source().replace("ScaleX", "ſcaleX")
        doc = formats.parse(text, "ass")
        self.assertIn("ſcalex", doc.style_fields)
        self.assertNotIn("scalex", doc.style_fields)
        self.assertIn("ſcalex", formats.serialize(doc, doc.cues))

    def test_non_ascii_indentation_does_not_activate_a_row(self):
        for prefix in ("\u00a0", "\u2003", " \ufeff"):
            with self.subTest(prefix=repr(prefix)), self.assertRaises(ValueError):
                formats.parse(source(extra=prefix + event("IGNORED")), "ass")

    def test_bom_then_ascii_indent_preserves_native_rows(self):
        text = source().replace("Dialogue:", "\ufeff\t Dialogue:")
        doc = formats.parse(text, "ass")
        self.assertEqual(doc.cues[0].text, "VISIBLE")
        self.assertEqual(formats.parse(formats.serialize(doc, doc.cues), "ass").cues[0].text, "VISIBLE")

    def test_renderer_active_section_suffixes_are_refused(self):
        for header in ("[Events]", "[V4+ Styles]", "[Script Info]"):
            for suffix in (" junk", "[]", "\u00a0"):
                with self.subTest(header=header, suffix=repr(suffix)), self.assertRaisesRegex(ValueError, "suffix"):
                    formats.parse(source().replace(header, header + suffix), "ass")

    def test_styles_after_events_require_deliberate_repair(self):
        text = source()
        prefix, remainder = text.split("[V4+ Styles]")
        styles, events = remainder.split("[Events]")
        with self.assertRaisesRegex(ValueError, "precede"):
            formats.parse(prefix + "[Events]" + events + "[V4+ Styles]" + styles, "ass")

    def test_active_unknown_section_refused(self):
        with self.assertRaisesRegex(ValueError, "outside"):
            formats.parse(source(extra="[Notes]\n" + event("UNREVIEWED")), "ass")

    def test_editor_unicode_and_graphics_sections_cannot_hide_events(self):
        for section in ("[Aegisub Project Garbage]", "[Graphics]", "[Eventſ]", "[Notes]"):
            for prefix in ("", "\t", "\ufeff "):
                with self.subTest(section=section, prefix=repr(prefix)), self.assertRaisesRegex(ValueError, "outside"):
                    formats.parse(source(extra=section + "\n" + prefix + event("UNREVIEWED")), "ass")

    def test_unknown_sections_cannot_hide_styles_or_track_controls(self):
        for row in (style("Hidden"), "Format: Name, Fontname", "PlayResX: 640", "Kerning: yes"):
            with self.subTest(label=row.split(":")[0]), self.assertRaisesRegex(ValueError, "outside"):
                formats.parse(source(extra="[Unknown]\n" + row), "ass")

    def test_harmless_metadata_and_opaque_fonts_are_retained(self):
        text = source(extra="[Notes]\nEditor: Authored\n[Aegisub Extradata]\nData: 0,key,value\n"
                            "[Fonts]\nfontname: authored.ttf\n!!!!\n[AAAA]\n;OPAQUE\n")
        doc = formats.parse(text, "ass")
        output = formats.serialize(doc, doc.cues)
        self.assertIn("Editor: Authored", output)
        self.assertIn("Data: 0,key,value", output)
        self.assertIn("[AAAA]\n;OPAQUE", output)
        self.assertNotIn("OPAQUE", formats.serialize(doc, doc.cues, remove_fonts=True))

    def test_import_refusal_is_transactional_and_retry_works(self):
        path = self.root / "input.ass"
        raw = source(extra="[Notes]\n" + event("UNREVIEWED")).encode("utf-8")
        path.write_bytes(raw)
        with self.assertRaisesRegex(ValueError, "outside"):
            workflow.prepare([path], self.work, "Authored track", 1, "utf-8", None, "en")
        self.assertFalse(self.work.exists())
        self.assertEqual(path.read_bytes(), raw)
        corrected = self.root / "corrected.ass"
        corrected.write_text(source(), encoding="utf-8")
        workflow.prepare([corrected], self.work, "Authored track", 1, "utf-8", None, "en")
        self.assertEqual(len(workflow.load(self.work)[1]["s0001"].cues), 1)

    def test_cli_refusal_has_no_traceback_or_publication(self):
        path = self.root / "input.ass"
        path.write_text(source(extra=event("Private fixture", label="dialogue")), encoding="utf-8")
        with self.assertRaisesRegex(ValueError, "canonical") as caught:
            runtime.run([sys.executable, str(SCRIPTS / "revayat-subtitle.py"), "prepare", str(path),
                         "--work", str(self.work), "--series", "Authored track", "--season", "1"], timeout=20)
        self.assertNotIn("Private fixture", str(caught.exception))
        self.assertNotIn("Traceback", str(caught.exception))
        self.assertFalse(self.work.exists())

    @unittest.skipUnless(RENDER, "Explicit FFmpeg integration tier")
    def test_native_ignored_row_and_unknown_section_oracles(self):
        clean = source()
        canonical = self.pixels("canonical", clean)
        self.assertGreater(max(canonical), 32)
        ignored = source(extra=event("IGNORED", label="dialogue"))
        self.assertEqual(self.pixels("ignored", ignored), canonical)
        with self.assertRaises(ValueError):
            formats.parse(ignored, "ass")
        hidden = source(extra="[Notes]\n" + event("UNREVIEWED"))
        self.assertNotEqual(self.pixels("unreviewed", hidden), canonical)
        with self.assertRaises(ValueError):
            formats.parse(hidden, "ass")


class StyleTests(TrackWorkspace):
    def test_style_collision_refused(self):
        for alias in ("*Alt", "**Alt", " Alt"):
            with self.subTest(alias=alias), self.assertRaisesRegex(ValueError, "Duplicate"):
                formats.parse(source([style("Alt"), style(alias)], name="Alt"), "ass")

    def test_event_default_alias_does_not_prune_the_actual_style(self):
        for alias in ("default", "DEFAULT", "*Default", "**dEfAuLt"):
            with self.subTest(alias=alias):
                doc = formats.parse(source([style("Default", "&H000000FF"), style("default", "&H0000FF00")], name=alias), "ass")
                output = formats.parse(formats.serialize(doc, doc.cues), "ass")
                self.assertEqual(set(output.styles), {"Default"})

    def test_significant_name_suffixes_and_unicode_space_remain_exact(self):
        for name in ("Alt ", "Alt\t", "Alt\u00a0", "\u00a0Alt", "\u2003Alt"):
            with self.subTest(name=repr(name)):
                doc = formats.parse(source([style(name)], name=name), "ass")
                self.assertEqual(set(doc.styles), {name})
                self.assertEqual(set(formats.parse(formats.serialize(doc, doc.cues), "ass").styles), {name})

    def test_unknown_exact_event_reference_is_not_silently_rebound(self):
        for declared, referenced in (("Alt ", "Alt"), ("Alt", "Alt "), ("\u00a0Alt", "Alt")):
            with self.subTest(declared=repr(declared), referenced=repr(referenced)):
                doc = formats.parse(source([style("Default"), style(declared)], name=referenced), "ass")
                with self.assertRaisesRegex(ValueError, "undefined"):
                    formats.serialize(doc, doc.cues)

    def test_anonymous_declared_name_resolves_to_default(self):
        for name in ("", "*", "**", "   "):
            with self.subTest(name=name):
                doc = formats.parse(source([style(name)]), "ass")
                self.assertEqual(set(doc.styles), {"Default"})
                self.assertEqual(len(formats.parse(formats.serialize(doc, doc.cues), "ass").cues), 1)

    def test_blank_style_row_is_not_silently_discarded(self):
        with self.assertRaisesRegex(ValueError, "Empty ASS Style"):
            formats.parse(source([style(), "Style: \t"]), "ass")

    def test_reset_arguments_keep_exact_unicode_names_and_spans(self):
        for tag, expected in ((r"{\r Alt}", " Alt"), (r"{\r( Alt )}", "Alt"),
                              ("{\\rAlt\u00a0}", "Alt\u00a0"), ("{\\r(\u00a0Alt)}", "\u00a0Alt")):
            with self.subTest(tag=repr(tag)):
                name, value, start, end = list(markup.overrides(tag))[0]
                self.assertEqual((name, value), ("r", expected))
                self.assertEqual(tag[start:end], expected)
                mapped = markup.remap_resets(tag, {expected: "Mapped"})
                self.assertEqual(mapped, tag[:start] + "Mapped" + tag[end:])

    def test_reset_and_event_alias_rules_are_not_conflated(self):
        for reset in (r"{\r*Alt}", r"{\rALT}", r"{\r Alt}"):
            with self.subTest(reset=reset):
                doc = formats.parse(source([style("Alt")], name="*Alt", text=reset + "VISIBLE"), "ass")
                with self.assertRaisesRegex(ValueError, "undefined"):
                    formats.serialize(doc, doc.cues)

    def test_default_named_reset_is_case_sensitive(self):
        doc = formats.parse(source([style(), style("default")], name="DEFAULT", text=r"{\rdefault}VISIBLE"), "ass")
        self.assertEqual(set(formats.parse(formats.serialize(doc, doc.cues), "ass").styles), {"Default", "default"})

    def test_donor_event_aliases_and_exact_resets_are_remapped(self):
        base = formats.parse(source(), "ass")
        donor = formats.parse(source([style("*Alt"), style("Tail\u00a0")], name="**Alt",
                             text="{\\rTail\u00a0}VISIBLE"), "ass")
        original = copy.deepcopy(donor)
        cues = workflow.merge_donor(base, donor, donor.cues, "s0002", True)
        self.assertEqual(cues[0].fields["style"], "s0002__Alt")
        self.assertIn("{\\rs0002__Tail\u00a0}", cues[0].text)
        self.assertEqual(donor, original)
        self.assertEqual(len(formats.parse(formats.serialize(base, cues), "ass").cues), 1)

    def test_failed_exact_donor_reset_is_atomic(self):
        base = formats.parse(source(), "ass")
        donor = formats.parse(source([style("Alt")], name="*Alt", text=r"{\r Alt}VISIBLE"), "ass")
        before = copy.deepcopy((base, donor))
        with self.assertRaises(ValueError):
            workflow.merge_donor(base, donor, donor.cues, "s0002", True)
        self.assertEqual((base, donor), before)
        donor.cues[0].text = r"{\rAlt}VISIBLE"
        self.assertEqual(workflow.merge_donor(base, donor, donor.cues, "s0002", True)[0].fields["style"], "s0002__Alt")

    def test_ascii_only_transform_argument_count_preserves_drawing(self):
        source_text = "{\\p1}m 0 0 l 20 0 20 20{\\t(0,100,1,\u00a0,\\p0)}m 30 0 l 50 0 50 20"
        self.assertEqual(formats.visible(source_text, "ass"), "")
        self.assertTrue(formats.has_drawing(source_text, "ass"))

    @unittest.skipUnless(RENDER, "Explicit FFmpeg integration tier")
    def test_native_style_alias_and_reset_raster_corpus(self):
        cases = [source([style("Default", "&H000000FF"), style("default", "&H0000FF00")], name="default"),
                 source([style("*Alt", "&H0000FF00")], name="**Alt"),
                 source([style("Alt ", "&H0000FF00")], name="Alt "),
                 source([style("\u00a0Alt", "&H0000FF00")], name="\u00a0Alt"),
                 source([style("Tail\u00a0", "&H0000FF00")], name="Tail\u00a0", text="{\\rTail\u00a0}VISIBLE"),
                 source([style("", "&H0000FF00")]),
                 source([style(), style("default", "&H0000FF00")], text=r"{\rdefault}VISIBLE")]
        for index, text in enumerate(cases):
            with self.subTest(index=index):
                doc = formats.parse(text, "ass")
                native = self.pixels(f"native-{index}", text)
                self.assertGreater(max(native), 32)
                self.assertEqual(native, self.pixels(f"emitted-{index}", formats.serialize(doc, doc.cues)))

        # The previous shared positive fixture contained a native-active empty
        # Style row. Keep that behavior as a negative oracle, not hidden cleanup.
        blank = source([style(), "Style: "])
        self.assertNotEqual(self.pixels("blank-style", blank), self.pixels("without-blank", source()))
        with self.assertRaisesRegex(ValueError, "Empty ASS Style"):
            formats.parse(blank, "ass")


class LegacyTests(TrackWorkspace):
    def test_unknown_section_generator_signature_is_refused(self):
        for section in ("[Notes]", "[Aegisub Project Garbage]", "[Graphics]"):
            for prefix in ("", "\t", "﻿ "):
                text = source(headers=section + "\n" + prefix + SIGNATURE)
                with self.subTest(section=section, prefix=repr(prefix)):
                    with self.assertRaisesRegex(ValueError, "outside"):
                        formats.parse(text, "ass")
        doc = formats.parse(source(headers="[Notes]\n; Harmless authored note"), "ass")
        self.assertEqual(len(doc.cues), 1)

    @unittest.skipUnless(RENDER, "Explicit FFmpeg integration tier")
    def test_native_unknown_section_signature_requires_refusal(self):
        text = source(headers="[Notes]\n" + SIGNATURE, text=r"{\bord8\shad4}VISIBLE")
        native = self.pixels("unknown-signature", text)
        self.assertGreater(max(native), 32)
        self.assertEqual(native, self.pixels("explicit-yes", text.replace(SIGNATURE, "ScaledBorderAndShadow: yes")))
        self.assertNotEqual(native, self.pixels("explicit-no", text.replace(SIGNATURE, "ScaledBorderAndShadow: no")))
        with self.assertRaisesRegex(ValueError, "outside"):
            formats.parse(text, "ass")

    def test_legacy_signature_scaling_materialized(self):
        doc = formats.parse(source(headers=SIGNATURE), "ass")
        self.assertIn("ScaledBorderAndShadow: yes", formats.serialize(doc, doc.cues))
        self.assertNotIn(SIGNATURE, formats.serialize(doc, doc.cues))

    def test_explicit_scaling_is_never_overridden(self):
        for setting in ("yes", "no"):
            with self.subTest(setting=setting):
                doc = formats.parse(source(headers=SIGNATURE + "\nScaledBorderAndShadow: " + setting), "ass")
                output = formats.serialize(doc, doc.cues)
                self.assertEqual(output.count("ScaledBorderAndShadow:"), 1)
                self.assertIn("ScaledBorderAndShadow: " + setting, output)

    def test_extra_renderer_headers_suppress_legacy_heuristic(self):
        for field in ("Kerning: no", "Language: en", "LayoutResX: 320", "LayoutResY: 180", "Timer: 100", "YCbCr Matrix: None", "WrapStyle: 0"):
            with self.subTest(field=field):
                doc = formats.parse(source(headers=SIGNATURE + "\n" + field), "ass")
                self.assertNotIn("ScaledBorderAndShadow:", formats.serialize(doc, doc.cues))

    def test_legacy_requires_exact_signature_and_style_count(self):
        for styles, headers in (([style(), style("Unused")], SIGNATURE), ([style()], SIGNATURE.lower()),
                                ([style("Alt")], SIGNATURE)):
            name = "Alt" if "Alt," in styles[0] else "Default"
            doc = formats.parse(source(styles, name=name, headers=headers), "ass")
            self.assertNotIn("ScaledBorderAndShadow:", formats.serialize(doc, doc.cues))

    def test_irrelevant_metadata_does_not_disable_real_legacy_scaling(self):
        for name in ("Default", "DefaultExtra", "*Default"):
            doc = formats.parse(source([style(name)], name=name, headers=SIGNATURE + "\nTitle: Authored\nCollisions: Normal"), "ass")
            self.assertIn("ScaledBorderAndShadow: yes", formats.serialize(doc, doc.cues))

    def test_legacy_donor_settings_are_checked_before_mutation(self):
        base = formats.parse(source(headers=SIGNATURE), "ass")
        donor = formats.parse(source(), "ass")
        before = copy.deepcopy(base)
        with self.assertRaisesRegex(ValueError, "scaledborderandshadow"):
            workflow.merge_donor(base, donor, donor.cues, "s0002", True)
        self.assertEqual(base, before)
        donor = formats.parse(source(headers="ScaledBorderAndShadow: yes"), "ass")
        cues = workflow.merge_donor(base, donor, donor.cues, "s0002", True)
        self.assertIn("ScaledBorderAndShadow: yes", formats.serialize(base, cues))

    def test_materialization_is_stable_across_serialization(self):
        doc = formats.parse(source(headers=SIGNATURE), "ass")
        first = formats.serialize(doc, doc.cues)
        again = formats.parse(first, "ass")
        self.assertEqual(formats.serialize(again, again.cues), first)

    def test_recipe_upgrade_preserves_source_reviews_and_old_edition(self):
        with patch.dict(workflow.GENERATION_RECIPE, {"version": 9, "normalization": 9}):
            old = Path(self.edition([source()])["build"])
        previous = {p.relative_to(self.work): p.read_bytes() for p in self.work.rglob("*") if p.is_file()}
        new = Path(workflow.build(self.work)["build"])
        self.assertNotEqual(old, new)
        self.assertEqual(previous, {p: (self.work / p).read_bytes() for p in previous})
        self.assertFalse((new / "renders").exists())

    @unittest.skipUnless(RENDER, "Explicit FFmpeg integration tier")
    def test_native_legacy_scaled_raster_is_preserved(self):
        text = source(headers=SIGNATURE, text=r"{\bord8\shad4}VISIBLE")
        doc = formats.parse(text, "ass")
        native = self.pixels("legacy-source", text)
        self.assertGreater(max(native), 32)
        self.assertEqual(native, self.pixels("legacy-fixed", formats.serialize(doc, doc.cues)))
        no = text.replace(SIGNATURE, "ScaledBorderAndShadow: no")
        self.assertNotEqual(native, self.pixels("legacy-negative", no))

    @unittest.skipUnless(RENDER, "Explicit FFmpeg integration tier")
    def test_complete_alias_and_legacy_build_render_delivery(self):
        texts = [source([style("Default", "&H000000FF"), style("default", "&H0000FF00")], name="default"),
                 source(headers=SIGNATURE, text=r"{\bord8}VISIBLE")]
        result = self.edition(texts)
        edition = Path(result["build"])
        snapshots = {p.relative_to(self.work): p.read_bytes() for folder in ("sources", "worksheets")
                     for p in (self.work / folder).iterdir()}
        for index, episode in enumerate(result["episodes"]):
            emitted = (edition / episode["file"]).read_text(encoding="utf-8")
            self.assertEqual(self.pixels(f"original-{index}", texts[index]), self.pixels(f"output-{index}", emitted))
            evidence = render.render(edition, episode["id"], None, None, None, False)
            review = runtime.read_json(Path(evidence["review"]))
            for frame in review["frames"]:
                frame.update(reviewed=True, note="Automated mechanical gate fixture, not human visual approval.")
            runtime.write_json(Path(evidence["review"]), review)
        self.assertTrue(render.qa(edition)["ok"])
        archive = self.root / "delivered.zip"
        render.package(edition, archive)
        with zipfile.ZipFile(archive) as package:
            self.assertEqual(package.namelist(), ["Sub/S01E01.ass", "Sub/S01E02.ass"])
            for episode in result["episodes"]:
                self.assertEqual(runtime.digest(package.read(episode["file"])), episode["sha256"])
        self.assertEqual(snapshots, {p: (self.work / p).read_bytes() for p in snapshots})
        self.assertEqual(workflow.build(self.work)["identity"], result["identity"])


if __name__ == "__main__":
    with runtime.operational_log("ass-track-audit"):
        unittest.main(verbosity=2)
