"""Strict ASS/SRT parsing and presentation-preserving subtitle transformations."""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from markup import SRT_BREAK, ARABIC, BIDI, PDF, RLE, RLM, overrides, pieces, rtl, uncomment, srt_tag_fits
from validation import MAX_TIME_MS

ASS_FIELDS = "Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"
STYLE_FIELDS = ("Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, "
                "BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, "
                "Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding")
DEFAULT_STYLE = ("Default,Arial,42,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,"
                 "0,0,0,0,100,100,0,0,1,2,1,2,30,30,35,1")


_ASS_CASE = str.maketrans("ABCDEFGHIJKLMNOPQRSTUVWXYZ", "abcdefghijklmnopqrstuvwxyz")
ASS_NATIVE_SECTIONS = frozenset({"[script info]", "[v4+ styles]", "[v4 styles]", "[events]", "[fonts]"})
ASS_RENDER_HEADERS = ("ScriptType", "PlayResX", "PlayResY", "LayoutResX", "LayoutResY",
                      "Timer", "WrapStyle", "ScaledBorderAndShadow", "Kerning", "YCbCr Matrix", "Language")


def ass_key(value: str) -> str:
    """Fold ASCII grammar names without changing Unicode identifiers or prose."""
    return value.translate(_ASS_CASE)


def ass_line_start(value: str) -> str:
    """Match the reader's BOM-then-ASCII-indent handling, not Unicode whitespace."""
    return value.lstrip("\ufeff").lstrip(" \t")


def ass_style_name(value: str, *, reference: bool = False) -> str:
    """Resolve declaration/event names; override resets use separate exact names."""
    name = value.lstrip(" \t").lstrip("*")
    if reference:
        return "Default" if ass_key(name) == "default" else name
    return name or "Default"


def _preserve_legacy_scaling(doc) -> None:
    """Materialize the renderer effect of legacy FFmpeg's non-display signature."""
    order = {ass_key(name): index for index, (name, _) in enumerate(doc.sections)}
    info_index, event_index = order.get("[script info]"), order.get("[events]")
    if (info_index is None or event_index is None or info_index > event_index
            or len(doc.styles) != 1 or not next(iter(doc.styles)).startswith("Default")):
        return
    lines = doc.sections[info_index][1]
    flags = set()
    for line in lines:
        raw = ass_line_start(line)
        for header in ASS_RENDER_HEADERS:
            if raw.startswith(header + ":"):
                flags.add(header)
        if raw.startswith("; Script generated by FFmpeg/Lavc"):
            flags.add("generator")
    if flags == {"ScriptType", "PlayResX", "PlayResY", "generator"}:
        # A copied donor or style pruning must not toggle the legacy heuristic.
        lines.append("ScaledBorderAndShadow: yes")


@dataclass
class Cue:
    id: str
    start: int
    end: int
    text: str
    fields: dict[str, str] = field(default_factory=dict)


@dataclass
class Document:
    kind: str
    cues: list[Cue]
    sections: list[tuple[str, list[str]]] = field(default_factory=list)
    event_fields: list[str] = field(default_factory=list)
    style_fields: list[str] = field(default_factory=list)
    styles: dict[str, list[str]] = field(default_factory=dict)
    comments: int = 0


def timestamp(value: str, kind: str) -> int:
    if not isinstance(value, str) or kind not in {"ass", "srt"}:
        raise ValueError("Invalid subtitle timestamp or format")
    pattern = (r"([0-9]{1,12}):([0-9]{2}):([0-9]{2})\.([0-9]{2})" if kind == "ass"
               else r"([0-9]{1,12}):([0-9]{2}):([0-9]{2}),([0-9]{3})")
    match = re.fullmatch(pattern, value.strip(" \t"))
    if not match:
        raise ValueError("Invalid subtitle timestamp")
    hours, minutes, seconds, fraction = map(int, match.groups())
    if minutes > 59 or seconds > 59:
        raise ValueError("Subtitle minutes and seconds must be below 60")
    result = ((hours * 60 + minutes) * 60 + seconds) * 1000 + fraction * (10 if kind == "ass" else 1)
    if result > MAX_TIME_MS:
        raise ValueError("Subtitle timestamp exceeds the supported millisecond limit")
    return result


def timecode(ms: int, kind: str) -> str:
    if type(ms) is not int or not 0 <= ms <= MAX_TIME_MS or kind not in {"ass", "srt"}:
        raise ValueError("Timestamp serialization requires nonnegative integer milliseconds and ASS/SRT")
    hours, ms = divmod(ms, 3600000)
    minutes, ms = divmod(ms, 60000)
    seconds, fraction = divmod(ms, 1000)
    if kind == "ass":
        return f"{hours}:{minutes:02}:{seconds:02}.{fraction // 10:02}"
    return f"{hours:02}:{minutes:02}:{seconds:02},{fraction:03}"


def effective_times(start: int, end: int, kind: str) -> tuple[int, int]:
    if type(start) is not int or type(end) is not int or not 0 <= start < end <= MAX_TIME_MS:
        raise ValueError("Cue timing requires nonnegative integers and end after start")
    result = (start // 10 * 10, end // 10 * 10) if kind == "ass" else (start, end)
    if result[1] <= result[0]:
        raise ValueError("Centisecond quantization collapses this cue; review its timing explicitly")
    return result


def parse(data: str, kind: str) -> Document:
    if not isinstance(data, str) or len(data) > 16 * 1024 * 1024:
        raise ValueError("Subtitle text exceeds the supported parse budget")
    data = data.lstrip("\ufeff").replace("\r\n", "\n").replace("\r", "\n")
    if "\x00" in data or "\ufffd" in data:
        raise ValueError("NUL or replacement characters in subtitles; check the input encoding")
    doc = Document(kind, [])
    if kind == "srt":
        def blocks():
            source, cursor = data.strip(), 0
            for match in re.finditer(r"\n[ \t]*\n", source):
                yield source[cursor:match.start()]
                cursor = match.end()
            yield source[cursor:]
        for block in blocks():
            if not block.strip():
                continue
            lines = block.split("\n")
            if len(lines) < 2 or not lines[0].strip().isdigit():
                raise ValueError("Malformed SRT cue; expected a number and timestamp line")
            times = lines[1].split(" --> ")
            if len(times) != 2:
                raise ValueError("Malformed SRT timestamp line")
            start, end = (timestamp(t, kind) for t in times)
            if len(doc.cues) >= 100000:
                raise ValueError("Subtitle exceeds 100000 cues")
            doc.cues.append(Cue(f"c{len(doc.cues) + 1:06}", start, end, "\n".join(lines[2:])))
    elif kind == "ass":
        section, lines = "", []
        seen_sections = set()
        known_sections = {"[script info]", "[v4+ styles]", "[v4 styles]", "[events]", "[fonts]",
                          "[graphics]", "[aegisub project garbage]", "[aegisub extradata]"}
        for line in data.split("\n"):
            stripped = ass_line_start(line).rstrip(" \t")
            folded = ass_key(stripped)
            if any(folded.startswith(name) for name in ASS_NATIVE_SECTIONS) and folded not in ASS_NATIVE_SECTIONS:
                raise ValueError("ASS section header has a renderer-active suffix; repair its spelling explicitly")
            header = stripped.startswith("[") and stripped.endswith("]")
            if ass_key(section) in {"[fonts]", "[graphics]"}:
                header = header and ass_key(stripped) in known_sections
            if header:
                section = stripped
                if ass_key(section) in seen_sections:
                    raise ValueError("Repeated ASS sections are not supported")
                seen_sections.add(ass_key(section))
                lines = []
                doc.sections.append((section, lines))
            elif section:
                lines.append(line)
            elif stripped and not stripped.startswith(";"):
                raise ValueError("ASS content before the first section")
        for section, lines in doc.sections:
            key = ass_key(section)
            if key not in {"[events]", "[v4+ styles]"}:
                if key == "[v4 styles]":
                    raise ValueError("Legacy SSA requires explicit conversion to ASS first")
                if key not in {"[script info]", "[fonts]"}:
                    prefixes = ("Format:", "Style:", "Dialogue:", "; Script generated by FFmpeg/Lavc",
                                *(header + ":" for header in ASS_RENDER_HEADERS))
                    if any(ass_line_start(line).startswith(prefixes) for line in lines):
                        raise ValueError("Renderer-active ASS row outside its supported section; repair a separate source copy")
                continue
            fields = []
            for line in lines:
                if not line.strip() or line.lstrip().startswith(";"):
                    continue
                label, separator, value = ass_line_start(line).partition(":")
                canonical = {"format": "Format", "style": "Style", "dialogue": "Dialogue", "comment": "Comment"}
                raw_label = label.lstrip(" \t")
                label = ass_key(raw_label)
                if label.strip(" \t") in canonical and raw_label != canonical[label.strip(" \t")]:
                    raise ValueError("ASS row labels require canonical spelling and no space before the colon")
                if not separator:
                    raise ValueError("Malformed ASS section row")
                if label == "format":
                    if fields:
                        raise ValueError("Multiple Format rows in an ASS section")
                    fields = [ass_key(s.strip(" \t")) for s in value.split(",")]
                    if len(fields) != len(set(fields)):
                        raise ValueError("Duplicate ASS Format fields")
                    if key == "[events]":
                        if not {"start", "end", "text", "style"} <= set(fields) or fields[-1] != "text":
                            raise ValueError("ASS Events requires Start, End, Style and final Text")
                        doc.event_fields = fields
                    else:
                        if "name" not in fields:
                            raise ValueError("ASS Styles requires a Name field")
                        doc.style_fields = fields
                elif label == "comment" and key == "[events]":
                    doc.comments += 1
                elif label == ("dialogue" if key == "[events]" else "style"):
                    if not value.strip(" \t") and label == "style":
                        raise ValueError("Empty ASS Style rows have renderer defaults; repair them explicitly")
                    if not fields:
                        raise ValueError("ASS rows require a preceding Format")
                    parts = value.lstrip(" \t").split(",", len(fields) - 1)
                    if len(parts) != len(fields):
                        raise ValueError("ASS row does not match its Format")
                    row = dict(zip(fields, parts))
                    if label == "style":
                        name = ass_style_name(row["name"])
                        if name in doc.styles:
                            raise ValueError("Duplicate ASS style name after renderer normalization")
                        doc.styles[name] = parts
                    else:
                        if len(doc.cues) >= 100000:
                            raise ValueError("Subtitle exceeds 100000 cues")
                        doc.cues.append(Cue(f"c{len(doc.cues) + 1:06}", timestamp(row["start"], kind),
                                            timestamp(row["end"], kind), row["text"], row))
                else:
                    raise ValueError("Unsupported ASS row in Events or Styles; inspect before conversion")
        if not doc.event_fields or not doc.style_fields:
            raise ValueError("Missing ASS Events or V4+ Styles Format")
        order = [ass_key(name) for name, _ in doc.sections]
        if order.index("[v4+ styles]") > order.index("[events]"):
            raise ValueError("ASS styles must precede events so style references resolve before rendering")
        _preserve_legacy_scaling(doc)
    else:
        raise ValueError("Supported formats are .ass and .srt")
    if not doc.cues:
        raise ValueError("No subtitle cues found")
    for cue in doc.cues:
        if cue.end <= cue.start:
            raise ValueError(f"Cue {cue.id} ends before or at its start")
    return doc


def visible(text: str, kind: str) -> str:
    result = "".join(value for type_, value in pieces(text, kind) if type_ == "text")
    if kind == "ass":
        result = result.replace(r"\N", "\n").replace(r"\n", " ").replace(r"\h", " ")
        result = result.replace(r"\{", "{").replace(r"\}", "}")
    return result.translate(str.maketrans("", "", BIDI)).strip()


def structure(text: str, kind: str) -> list[tuple[str, str]]:
    return [(type_, value) for type_, value in pieces(text, kind) if type_ != "text"]


def has_drawing(text: str, kind: str) -> bool:
    return any(type_ == "drawing" and value.strip() for type_, value in pieces(text, kind))


def style_references(cue: Cue) -> set[str]:
    refs = {ass_style_name(cue.fields.get("style", "Default"), reference=True)}
    for type_, value in pieces(cue.text, "ass"):
        if type_ == "tag":
            refs.update(argument for name, argument, _, _ in overrides(value)
                        if name == "r" and argument)
    return refs


def serialize(doc: Document, cues: list[Cue], remove_fonts: bool = False) -> str:
    cues = sorted(cues, key=lambda cue: cue.start)  # Ties retain their source/layer order.
    if not cues:
        raise ValueError("Refusing an episode with no retained cues")
    for cue in cues:
        effective_times(cue.start, cue.end, doc.kind)
    if doc.kind == "srt":
        return "\n\n".join(f"{i}\n{timecode(c.start, 'srt')} --> {timecode(c.end, 'srt')}\n{c.text}"
                           for i, c in enumerate(cues, 1)) + "\n"
    used = set().union(*(style_references(c) for c in cues))
    if used - doc.styles.keys():
        raise ValueError("Subtitle references an undefined ASS style")
    output = []
    for name, lines in doc.sections:
        key = ass_key(name)
        if key == "[aegisub project garbage]" or (remove_fonts and key == "[fonts]"):
            continue
        output.append(name)
        if key == "[events]":
            output.append("Format: " + ", ".join(doc.event_fields))
            for cue in cues:
                row = {**cue.fields, "start": timecode(cue.start, "ass"), "end": timecode(cue.end, "ass"),
                       "text": cue.text}
                if "\n" in cue.text or "\r" in cue.text:
                    raise ValueError("ASS cue text must use literal \\N instead of a physical newline")
                output.append("Dialogue: " + ",".join(row.get(field_, "") for field_ in doc.event_fields))
        elif key == "[v4+ styles]":
            output.append("Format: " + ", ".join(doc.style_fields))
            output.extend("Style: " + ",".join(values) for style, values in doc.styles.items() if style in used)
        else:
            output.extend(line for line in lines if line.strip() and
                          (key in {"[fonts]", "[graphics]"} or not line.lstrip().startswith(";")))
        output.append("")
    return "\n".join(output)


def validate_srt_donor_markup(text: str) -> None:
    """Refuse unimplemented decoder markup rather than expose it as ASS prose."""
    for match in re.finditer(r"<([^<>]{0,128})>", text):
        if not srt_tag_fits(match[0]):
            continue
        body = match[1]
        closing = body.startswith("/")
        body = body[1:] if closing else body
        name = body.lstrip(" ").split(" ", 1)[0]
        recognized = name.lower() in {"b", "i", "s", "u", "font", "br", "br/"}
        likely = (re.fullmatch(r"[A-Za-z0-9_/]*", name) is not None
                  and not body.startswith(" ")
                  and (closing or match.start() == 0 or text[match.start() - 1] != "<"))
        supported = (SRT_BREAK.fullmatch(match[0]) is not None
                     or re.fullmatch(r"</?[bisu]>", match[0], re.I | re.ASCII) is not None)
        if (recognized or likely) and not supported:
            raise ValueError("SRT donor uses unsupported decoder markup; adapt it explicitly before ASS conversion")


def srt_to_ass(cue: Cue) -> Cue:
    text = uncomment(cue.text.replace("\r\n", "\n").replace("\r", "\n"), "srt")
    validate_srt_donor_markup(text)
    if any(char in text for char in ("{", "}", "\\")):
        raise ValueError("SRT donor contains ASS control syntax; adapt it explicitly before ASS conversion")
    text = SRT_BREAK.sub(lambda match: "\n" if srt_tag_fits(match[0]) else match[0], text)
    for tag in ("i", "b", "u", "s"):
        ass_tag = "s" if tag == "s" else tag
        text = re.sub(f"<{tag}>", lambda _: "{\\" + ass_tag + "1}", text, flags=re.I | re.ASCII)
        text = re.sub(f"</{tag}>", lambda _: "{\\" + ass_tag + "0}", text, flags=re.I | re.ASCII)
    if any(type_ == "tag" for type_, _ in pieces(text, "srt")):
        raise ValueError("SRT donor uses markup requiring explicit ASS adaptation")
    fields = dict(zip([f.strip().lower() for f in ASS_FIELDS.split(",")],
                      ["0", "", "", "Default", "", "0", "0", "0", "", ""]))
    start, end = effective_times(cue.start, cue.end, "ass")
    return Cue(cue.id, start, end, text.replace("\n", r"\N"), fields)
